# Generated by Django 3.2.12 on 2022-05-11 01:00

from django.db import migrations
import uuid

def gen_uuid(apps,schema_editor):
    subscriptions = apps.get_model('subscriptions', 'subscription')
    for row in subscriptions.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['temp_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscription_temp_id'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)
    ]
