# Generated by Django 3.2.12 on 2022-05-11 01:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_auto_20220511_0100'),
    ]

    operations = {
        migrations.AlterField(
            model_name='subscription',
            name='temp_id',
            field=models.UUIDField(primary_key=True, default=uuid.uuid4, unique=True),
        ),
    }
