# Generated by Django 3.2.12 on 2022-05-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_auto_20220510_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='temp_id',
            new_name='id',
        ),
    ]
