# Generated by Django 3.2.12 on 2022-05-11 01:08
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20220511_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='id',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='temp_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        )
    ]
