# Generated by Django 3.2.12 on 2022-05-11 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20220511_0107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='temp_id',
            new_name='id',
        ),
    ]
