# Generated by Django 3.2.12 on 2022-11-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_courseold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talk',
            options={'ordering': ['start'], 'verbose_name': 'palestra', 'verbose_name_plural': 'palestras'},
        ),
    ]
